---
- name: install software needed to for dspace and other needed utilities
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - xpdf
    - lrzip
    - iotop
    - mtr
    - links
    - htop
    - vim
    - libmagick++-dev
    - imagemagick
    - ghostscript
    - unzip
    - maven
    - clamav
    - clamav-daemon

- name: copy template for clamd
  template: src=clamd.conf.j2 dest=/etc/clamav/clamd.conf

- name: start freshclam
  command: /usr/bin/freshclam --quiet

- name: restart clamav
  service: name=clamav-daemon state=restarted
