---
- name: install software needed to for dspace and other needed utilities
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - xpdf
    - lrzip
    - iotop
    - mtr
    - links
    - htop
    - vim
    - libmagick++-dev
    - imagemagick
    - ghostscript
    - unzip
    - maven
    - build-essential
