---
- name: ensure ant debian package is not installed
  apt: name=ant state=absent

- name: download ant binary
  get_url: url=http://apache.mirrors.lucidnetworks.net/ant/binaries/apache-ant-{{ ant_version }}-bin.tar.gz dest=/tmp/apache-ant-{{ ant_version }}-bin.tar.gz

- name: unpack downloaded ant binary
  unarchive: src=/tmp/apache-ant-{{ ant_version }}-bin.tar.gz dest={{ software_directory }} remote_src=yes creates=yes copy=no

- name: create symbolic link for ant
  file: src={{ software_directory }}/apache-ant-{{ ant_version }} dest=/opt/apache-ant state=link

- name: override system ant modules
  shell: echo 'export PATH="/opt/apache-ant/bin:$PATH"' > /etc/profile.d/ant.sh creates=/etc/profile.d/ant.sh
