---
apache_listen_port: 80

apache_create_vhosts: true
apache_vhosts_filename: "vhosts.conf"


apache_vhosts:
  # Additional properties: 'serveradmin, serveralias, extra_parameters'.
  - servername: "{{ ansible_hostname }}"
    documentroot: "/var/www/html"

apache_vhosts_ssl: []
  # Additional properties: 'serveradmin, extra_parameters'.
  # - servername: "local.dev",
  #   documentroot: "/var/www/html",
  #   certificate_file: "/path/to/certificate.crt",
  #   certificate_key_file: "/path/to/certificate.key",
  #   # Optional.
  #   certificate_chain_file: "/path/to/certificate_chain.crt"



# Only used on Debian/Ubuntu.
apache_mods_enabled:
  - rewrite.load
  - proxy_http.load
  - proxy.load
  - shib2.load

apache_mods_disabled: []

# Set initial apache state. Recommended values: `started` or `stopped`
apache_state: started

