---
- name: create project database role
  postgresql_user:
    name: 'dspace'
    password: 'dspace'
    role_attr_flags: CREATEDB

- name: create project database
  postgresql_db:
    name: 'dspace'
    encoding: 'UTF-8'
    owner: 'dspace'
