# privileged user running playbook
ansible_user: "vagrant"

# user under which the vtechworks will run
project_user: "vtechworks"
# the home directory of vtechworks user
project_user_home: "/var/local/{{ project_user }}"
# name of the group vtechworks user belongs
project_group: "{{ project_user }}"

# directory for non deb software
software_directory: "/opt/nondeb"

# The PostgreSQL user used to create the application PostgreSQL database
database_user: 'postgres'
database_group: 'postgres'
database_password: 'postgres'
# database user
database_url: 'jdbc:postgresql://localhost:5432/dspace'
database_user_password: 'dspace'

# vtechworks variables

dspace_source_dir: '{{ project_user_home }}/src'
source_dir: "{{ dspace_source_dir }}"
project_repo_url: "https://github.com/VTUL/vtechworks.git"
dspace_repo_version: 'vt_5_x_dev_deploy'
version: '{{ repo_version }}'
repo_version: '{{ dspace_repo_version }}'
ga_key: 'UA-4123456-11'


##### elements
elenvironment: '1.2.3.4|2.3.4.5|3.4.5.6|4.5.6.7'
elpublicurl: 'ed.lib.vt.edu'

# errata config
assetstore: 1
nfs_share: '1.2.3.4'
unix_assets: 'Unix_asset_store'
